#!/usr/bin/env bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias clr="clear"
alias o="open"
alias oo="open ."

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
else # macOS `ls`
	colorflag="-G"
fi

alias l="ls -lF ${colorflag}"
alias ls="command ls ${colorflag}"
alias ll="ls -lAF ${colorflag}"

alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias vim="nvim"
