#!/usr/bin/env bash


export EDITOR='vim'
export GREP_OPTIONS="--color=auto"
export GREP_COLOR="1;32"

# History ----------------------------------------------------------------------
export HISTSIZE=10000
export HISTFILESIZE=20000
# don't put duplicate lines in the history
export HISTCONTROL=ignoreboth:erasedups
# don't add to history matching cmds
export HISTIGNORE="&:bg:fg:exit:history:clear"


# Environment ------------------------------------------------------------------
export LANGUAGE="en_US.utf-8"
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"


# Python -----------------------------------------------------------------------
# Make python use UTF-8 encoding
export PYTHONENCODING='UTF-8'
# export VIRTUAL_ENV_DISABLE_PROMPT=1

